
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Enable API
api:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named packages
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
