sensor:
######### Sony Bravia KDL-55W805B ###########
############# Power Sensor ##########
  - platform: rest
    name: Sony Bravia TV Power Status
    resource_template: !secret bravia_systemurl
    headers:
      x-auth-psk: !secret bravia_psk
    method: POST
    payload: '{"method":"getPowerStatus","params":[""],"id":1,"version":"1.0"}'
    value_template:  >
      {%- if value_json is defined -%}
        {{- value_json.result[0].status -}}
      {%- else -%}
        offline
      {%- endif -%}
    scan_interval: 604800
############# Current Picture Mode Sensor ##########
  - platform: rest
    name: Sony Bravia TV Current Picture Mode
    resource_template: !secret bravia_videoscreenurl
    headers:
      x-auth-psk: !secret bravia_psk
    method: POST
    payload: '{"method":"getPictureQualitySettings","params":[{"target":"pictureMode"}],"id":52,"version":"1.0"}'
    value_template:  >
      {%- if value_json is defined -%}
        {{- value_json.result[0][0].currentValue -}}
      {%- else -%}
        auto
      {%- endif -%}
    scan_interval: 604800
############# All Picture Modes Sensor #############
  - platform: rest
    name: Sony Bravia TV Picture Mode Setting
    resource_template: !secret bravia_videoscreenurl
    headers:
      x-auth-psk: !secret bravia_psk
    method: POST
    payload: '{"method":"getPictureQualitySettings","params":[{"target":"pictureMode"}],"id":52,"version":"1.0"}'
    json_attributes_path: "$.result.[0][0]"
    json_attributes:
      - candidate
      - currentValue
    value_template:  'OK'

rest_command:
######### Sony Bravia KDL-55W805B ###########
############ Set Picture Mode Command ##############
  bravia_picture_mode:
    url: !secret bravia_videoscreenurl
    method: POST
    headers:
      x-auth-psk: !secret bravia_psk
      accept: 'application/json'
    payload: '{"method":"setPictureQualitySettings","params":[{"settings":[{"target":"pictureMode","value":"{{ picturemode }}"}]}],"id":40,"version": "1.0" }'
    content_type:  'application/json; charset=utf-8'
