automation:
  - id: '1644689563987'
    alias: TV Surround Sound/Picture Mode
    description: Set receiver to 5.1 surround and TV to game mode for select ATV apps
    variables:
      rc:
        apps: ['com.s0und.s0undtv', 'com.swordfish.lemuroid']
        default: 'straight'
        trigger: '5ch_stereo'
      tv:
        apps: ['com.s0und.s0undtv', 'com.swordfish.lemuroid', 'com.nvidia.tegrazone3']
        sensor: 'sensor.sony_bravia_tv_current_picture_mode'
        default: 'custom'
        trigger: 'game'
      bl:
        apps: ['com.swordfish.lemuroid']
        default: [255, 180, 107]
        trigger: [42, 235, 74]
    trigger:
    - platform: state
      entity_id: media_player.living_shield
      attribute: app_name
      variables:
        curr_app: "{{ state_attr('media_player.living_shield', 'app_name') }}"
    condition: "{{ not is_state('media_player.living_shield', 'off') }}"
    action:
    - service: homeassistant.update_entity
      entity_id: sensor.sony_bravia_tv_current_picture_mode
    - condition: or
      conditions:
      - condition: template
        value_template: "{{ curr_app in tv.apps and not is_state(tv.sensor, tv.trigger) }}"
      - condition: template
        value_template: "{{ curr_app not in tv.apps and not is_state(tv.sensor, tv.default) }}"
    - service: rest_command.bravia_picture_mode
      data_template:
        picturemode: >
          {% if curr_app in tv.apps %}
            {{ tv.trigger }}
          {% else %}
            {{ tv.default }}
          {% endif %}
    - service: media_player.select_sound_mode
      target:
        entity_id: media_player.rx_v481_dc8155 
      data_template:
        sound_mode: >
          {% if curr_app in rc.apps %}
            {{ rc.trigger }}
          {% else %}
            {{ rc.default }}
          {% endif %}
    - service: light.turn_on
      target:
        entity_id: light.hue_lightstrip_plus_1
      data_template:
        rgb_color: >
          {% if curr_app in bl.apps %}
            {{ bl.trigger }}
          {% else %}
            {{ bl.default }}
          {% endif %}
    - service: homeassistant.update_entity
      entity_id: sensor.sony_bravia_tv_current_picture_mode
    mode: single
